# Generated by Django 5.1.3 on 2024-11-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('externalid', models.TextField(db_column='externalId', primary_key=True, serialize=False)),
                ('area_raw', models.TextField(blank=True, db_column='areaRaw', null=True)),
                ('area_sqm', models.IntegerField(blank=True, db_column='areaSqm', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cover_image_url', models.URLField(blank=True, db_column='coverImageUrl', null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description_translated', models.TextField(blank=True, db_column='descriptionTranslated', null=True)),
                ('description_non_translated', models.TextField(blank=True, db_column='descriptionNonTranslated', null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(db_column='userId', primary_key=True, serialize=False)),
                ('user_display_name', models.TextField(blank=True, db_column='userDisplayName', null=True)),
                ('user_photo_url', models.TextField(blank=True, db_column='userPhotoUrl', null=True)),
                ('user_last_logged_on', models.TextField(blank=True, db_column='userLastLoggedOn', null=True)),
                ('user_member_since', models.TextField(blank=True, db_column='userMemberSince', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_age', models.TextField(blank=True, db_column='matchAge', null=True)),
                ('match_capacity', models.TextField(blank=True, db_column='matchCapacity', null=True)),
                ('match_gender', models.TextField(blank=True, db_column='matchGender', null=True)),
                ('match_status', models.TextField(blank=True, db_column='matchStatus', null=True)),
                ('match_languages', models.TextField(blank=True, db_column='matchLanguages', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_info', to='store.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_detail', models.TextField(blank=True, db_column='rentDetail', null=True)),
                ('rent_raw', models.TextField(blank=True, db_column='rentRaw', null=True)),
                ('registration_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_cost_raw', models.TextField(blank=True, db_column='registrationCostRaw', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_info', to='store.property')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.matchinfo')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.property')),
                ('rent_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.rentinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
    ]
