# Generated by Django 5.1.3 on 2024-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('externalid', models.TextField(blank=True, db_column='externalId', primary_key=True, serialize=False)),
                ('arearaw', models.TextField(blank=True, db_column='areaRaw', null=True)),
                ('areasqm', models.IntegerField(blank=True, db_column='areaSqm', null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('coverimageurl', models.TextField(blank=True, db_column='coverImageUrl', null=True)),
                ('furnish', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('postalcode', models.TextField(blank=True, db_column='postalCode', null=True)),
                ('postedago', models.TextField(blank=True, db_column='postedAgo', null=True)),
                ('propertytype', models.TextField(blank=True, db_column='propertyType', null=True)),
                ('rawavailability', models.TextField(blank=True, db_column='rawAvailability', null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('rentdetail', models.TextField(blank=True, db_column='rentDetail', null=True)),
                ('rentraw', models.TextField(blank=True, db_column='rentRaw', null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('additionalcosts', models.FloatField(blank=True, db_column='additionalCosts', null=True)),
                ('additionalcostsraw', models.TextField(blank=True, db_column='additionalCostsRaw', null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('depositraw', models.TextField(blank=True, db_column='depositRaw', null=True)),
                ('descriptionnontranslated', models.TextField(blank=True, db_column='descriptionNonTranslated', null=True)),
                ('descriptionnontranslatedraw', models.TextField(blank=True, db_column='descriptionNonTranslatedRaw', null=True)),
                ('descriptiontranslated', models.TextField(blank=True, db_column='descriptionTranslated', null=True)),
                ('descriptiontranslatedraw', models.TextField(blank=True, db_column='descriptionTranslatedRaw', null=True)),
                ('energylabel', models.TextField(blank=True, db_column='energyLabel', null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('internet', models.TextField(blank=True, null=True)),
                ('isroomactive', models.TextField(blank=True, db_column='isRoomActive', null=True)),
                ('kitchen', models.TextField(blank=True, null=True)),
                ('living', models.TextField(blank=True, null=True)),
                ('matchage', models.TextField(blank=True, db_column='matchAge', null=True)),
                ('matchagebackup', models.TextField(blank=True, db_column='matchAgeBackup', null=True)),
                ('matchcapacity', models.TextField(blank=True, db_column='matchCapacity', null=True)),
                ('matchgender', models.TextField(blank=True, db_column='matchGender', null=True)),
                ('matchgenderbackup', models.TextField(blank=True, db_column='matchGenderBackup', null=True)),
                ('matchlanguages', models.TextField(blank=True, db_column='matchLanguages', null=True)),
                ('matchstatus', models.TextField(blank=True, db_column='matchStatus', null=True)),
                ('matchstatusbackup', models.TextField(blank=True, db_column='matchStatusBackup', null=True)),
                ('pagedescription', models.TextField(blank=True, db_column='pageDescription', null=True)),
                ('pagetitle', models.TextField(blank=True, db_column='pageTitle', null=True)),
                ('pets', models.TextField(blank=True, null=True)),
                ('registrationcost', models.TextField(blank=True, db_column='registrationCost', null=True)),
                ('registrationcostraw', models.TextField(blank=True, db_column='registrationCostRaw', null=True)),
                ('roommates', models.TextField(blank=True, null=True)),
                ('shower', models.TextField(blank=True, null=True)),
                ('smokinginside', models.TextField(blank=True, db_column='smokingInside', null=True)),
                ('toilet', models.TextField(blank=True, null=True)),
                ('userdisplayname', models.TextField(blank=True, db_column='userDisplayName', null=True)),
                ('userid', models.TextField(blank=True, db_column='userId', null=True)),
                ('userlastloggedon', models.TextField(blank=True, db_column='userLastLoggedOn', null=True)),
                ('usermembersince', models.TextField(blank=True, db_column='userMemberSince', null=True)),
                ('userphotourl', models.TextField(blank=True, db_column='userPhotoUrl', null=True)),
                ('field_id_oid', models.TextField(blank=True, db_column='_id.$oid', null=True)),
                ('firstseenat_date', models.TextField(blank=True, db_column='firstSeenAt.$date', null=True)),
                ('lastseenat_date', models.TextField(blank=True, db_column='lastSeenAt.$date', null=True)),
                ('additionalcostsdescription', models.TextField(blank=True, db_column='additionalCostsDescription', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchinfo',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyfeature',
            name='property',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='MatchInfo',
        ),
        migrations.DeleteModel(
            name='RentInfo',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyFeature',
        ),
    ]
