# Generated by Django 5.1.3 on 2024-12-01 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('store', '0002_properties_remove_matchinfo_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('properties', models.ManyToManyField(related_name='wishlists', to='store.properties')),
            ],
        ),
    ]
